# Project infromation
project:
  name: "Cancer Detection"
  description: "DPL302m Project - Fall 2024 of Group 1"
  author: "Group 1"
  version: "1.0.0"

# Filesystem configuration
data:
  data_path: "data/"
  raw_path: "data/raw/"
  raw_csv_path: "data/raw/HAM10000_metadata.csv"
  raw_images_path: "data/raw/images/"

  processed_path: "data/processed/"
  # processed_csv_path: "data/processed/HAM10000_metadata.csv"
  processed_images_path: "data/processed/images/"


# Cần phân chia cả raw và preprocessed data ở đây ( ở trên)

# Hyperparameters
hyperparameters:
  epochs: 50
  batch_size: 32
  learning_rate: 0.001
  test_size: 0.2
  random_state: 42
  num_classes: 7
  feature_extract: False


# Preprocessing configuration
preprocessing:
  augmentation:
    ratio: 1
  resize: !!seq [224, 224]
  desired_total: 20000


# Training configuration

processor:
  n_workers: 16
  batch_size: 32
  test_size: 0.2
  random_state: 42
  
# Encoder location
encoder:
  path: "encoder/"

# Model configuration

# Data augmentation

# Hardware configuration

# Logging configuration

# Connect with GG Colab
#http://localhost:8888/tree?token=a1b385127099649cebd63e1c4964b1c02c1585eb8238c667
#http://127.0.0.1:8888/tree?token=a1b385127099649cebd63e1c4964b1c02c1585eb8238c667